### ISSUE TITLE
SuperCell asserts C-link

### ISSUE THREAD

**Issue by nwmoriarty** [qrefine/qrefine#11]
Using the qr-test-1yjp running

qr.refine 1yjp_complete.pdb_modified.pdb 1yjp.mtz debug=1 clustering=1 restraints=cctbx

causes (if you comment the try/except @ line 193 in driver.py)

***********************************************************
restart info will be stored in pdb/1yjp_complete.pdb_modified.rst.pickle
***********************************************************

Start:
     0 Rw: 0.1679 Rf: 0.1762 Rf-Rw: 0.0083 rmsd(b):  0.0140 rws:  1.000 n_fev: 0
Optimal weight search:
Traceback (most recent call last):
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/build/../modules/qrefine/command_line/refine.py", line 116, in <module>
    run(args=sys.argv[1:], log=log)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/build/../modules/qrefine/command_line/refine.py", line 111, in run
    log      = log)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/qr.py", line 391, in run
    results               = results_manager)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/driver.py", line 298, in refine
    results=results, geometry_rmsd_manager=geometry_rmsd_manager)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/driver.py", line 201, in run_minimize
    geometry_rmsd_manager = geometry_rmsd_manager)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/driver.py", line 116, in __init__
    ignore_search_direction_not_descent=True
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 278, in run
    line_search)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/cctbx_project/scitbx/lbfgs/__init__.py", line 131, in run_c_plus_plus
    f, g = target_evaluator.compute_functional_and_gradients()
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/driver.py", line 142, in compute_functional_and_gradients
    return self.calculator.target_and_gradients(x = self.x)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/calculator.py", line 212, in target_and_gradients
    rt, rg = self.restraints_manager.target_and_gradients(sites_cart = self.x)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/cluster_restraints.py", line 24, in target_and_gradients
    expansion.update_xyz(sites_cart=sites_cart).ph_super_sphere
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/super_cell.py", line 213, in update_xyz
    self.update(sites_cart=sites_cart, selection_r=self.selection_r)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/super_cell.py", line 202, in update
    r                    = selection_r)
  File "/Users/nigel/phenix/phenix-1.14rc1-3161/modules/qrefine/super_cell.py", line 141, in create_super_sphere
    assert n_linked in [1, 0], n_linked # Either linked or not!

**Comment by pafonine** [comment]
Cannot reproduce this crash perhaps because I'm using 1yjp (completed) from PDB and not 1yjp_complete.pdb_modified.pdb quoted in original post.
