### ISSUE TITLE
PyScf engine not working

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#28]
**The bug**
When I try and use PyScf it fails. 

**To Reproduce**
 qr.refine 1uso.pdb mode=opt restraints=qm engine_name=pyscf

 No function available to set basis to STO-3G
  No function available to set method to HF
Traceback (most recent call last):
  File "/Users/mark/PycharmProjects/phenix/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 144, in <module>
    run(args=sys.argv[1:], log=log)
  File "/Users/mark/PycharmProjects/phenix/phenix-dev-3386/build/../modules/qrefine/command_line/refine.py", line 138, in run
    log      = log)
  File "/Users/mark/PycharmProjects/phenix/phenix-dev-3386/modules/qrefine/qr.py", line 454, in run
    model            = model)
  File "/Users/mark/PycharmProjects/phenix/phenix-dev-3386/modules/qrefine/qr.py", line 319, in create_restraints_manager
    clustering                 = params.cluster.clustering)
  File "/Users/mark/PycharmProjects/phenix/phenix-dev-3386/modules/qrefine/restraints.py", line 103, in __init__
    self.qm_engine.command = self.qm_engine.get_command()

**Expected behavior**
The optimisation should run with the pyscf engine.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.2
 - Version v1.0-19-ga7e1184

**Comment by mpwaller** [comment]
pyscf wrapper run() method changed to run_qr() and updated to match newer restraints. This gets calculator working again, now need to write unit test.

**Comment by mpwaller** [comment]
unit test added
