### ISSUE TITLE
1kyc fails with clustering=true

### ISSUE THREAD

**Issue by biczysko** [qrefine/qrefine#30]
**Describe the bug**
Running any qr.refine job (opt/refine, restrains=cctbx/qm)  with clustering=true for 1kyc fails

**To Reproduce**
qr.refine 1kyc_refine_001-coot-2_refine_001.pdb mode=opt clustering=true restraints=cctbx 

***********************************************************
restart info will be stored in /home/malgo/QR/1kyc/OPT/pdb/1kyc_refine_001-coot-2_refine_001.rst.pickle
***********************************************************

Traceback (most recent call last):
  File "/home/malgo/phenix-dev-3385/build/../modules/qrefine/command_line/refine.py", line 144, in <module>
    run(args=sys.argv[1:], log=log)
  File "/home/malgo/phenix-dev-3385/build/../modules/qrefine/command_line/refine.py", line 138, in run
    log      = log)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/qr.py", line 451, in run
    crystal_symmetry = model.xray_structure.crystal_symmetry())
  File "/home/malgo/phenix-dev-3385/modules/qrefine/qr.py", line 296, in create_fragment_manager
    charge_cutoff              = params.cluster.charge_cutoff)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/fragment.py", line 85, in __init__
    select_within_radius = 10.0)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/super_cell.py", line 193, in __init__
    self.update()
  File "/home/malgo/phenix-dev-3385/modules/qrefine/super_cell.py", line 202, in update
    r                    = selection_r)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/super_cell.py", line 155, in create_super_sphere
    n_linked, rgj = grow_chain(residue_groups_j, chunk, ci)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/super_cell.py", line 111, in grow_chain
    d_ci_nj = dist(ci,nj)
  File "/home/malgo/phenix-dev-3385/modules/qrefine/super_cell.py", line 104, in dist
    return math.sqrt((r1[0]-r2[0])**2+(r1[1]-r2[1])**2+(r1[2]-r2[2])**2)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Expected behavior**
Define clusters and start run single jobs

**Desktop (please complete the following information):**
 - OS: gqms, 3.10.0-327.el7.x86_64 GNU/Linux
 - Version:  v1.0-3-gd64486

**Additional context**
1. Bug was discovered with xtb computations, but it is also reproduced using cctbx.
2. pdb created by Pavel on 29 Oct "Should be ready to qr-refine."
3. Same bug in qr.refine computation on 29 Oct 2018.
[1kyc_refine_001-coot-2_refine_001_pdb.zip](https://github.com/qrefine/qrefine/files/2790761/1kyc_refine_001-coot-2_refine_001_pdb.zip)

**Comment by pafonine** [comment]
I've just committed a fix for this crash.
Pavel

**Comment by pafonine** [comment]
I'm not closing the issue because the command still crash in pyoink.py.

**Comment by biczysko** [comment]
Running gtest for this file I get following error printout:

Starting loop over different fragment sizes
loop for g_mode = 1
g_mode: 1 - 5
~max cluster size  5
Sorry: Fatal problems interpreting model file:
  Number of atoms with unknown nonbonded energy type symbols: 1
    Please edit the model file to resolve the problems and/or supply a
    CIF file with matching restraint definitions, along with
    apply_cif_modification and apply_cif_link parameter definitions
    if necessary.

**Comment by pafonine** [comment]
This is another problem from my list of immediate issues that we should 
fix before writing papers: qr.refine does not work if input PDB file 
contains a non-standard amino-acid residue. 1kyc contains such residue 
(called SIN, if I remember correctly).
Pavel

**Comment by biczysko** [comment]
OK, yes it contains SIN residue.

**Comment by pafonine** [comment]
It seems to work now.
