### ISSUE TITLE
qr.charges/ qr.restraint fails for protein containg Fe atom

### ISSUE THREAD

**Issue by rajeevroy09** [qrefine/qrefine#51]
Hi, 

I am trying to refine a protein file (pdbid: 1iro) which contains an Iron (Fe) atom. 

qr.charges as well as qs.restraint both failed with the same AssertionError i.e. element Fe not found. 

I am pasting the output I got after running both commands:

------------qr.charges-------------
"Starting Q|R charge
version:   v1.0-114-g3318f9  
Traceback (most recent call last):
  File "/scratch/roy/programs/phenix-1.16-3549/build/../modules/qrefine/command_line/charge.py", line 106, in <module>
    run(args=sys.argv[1:], log=log)
  File "/scratch/roy/programs/phenix-1.16-3549/build/../modules/qrefine/command_line/charge.py", line 94, in run
    assert_correct_chain_terminii=params.assert_correct_chain_terminii,
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/charges.py", line 159, in get_total_charge
    verbose=verbose,
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/utils/electrons.py", line 427, in run
    verbose=verbose,
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/utils/electrons.py", line 74, in __init__
    assert e is not None, ' element %s not found' % atom.element
AssertionError:  element Fe not found

--------------qr.restraint----------------------------
Traceback (most recent call last):
  File "/scratch/roy/programs/phenix-1.16-3549/build/../modules/qrefine/command_line/restraint.py", line 99, in <module>
    run(args=sys.argv[1:], log=log)
  File "/scratch/roy/programs/phenix-1.16-3549/build/../modules/qrefine/command_line/restraint.py", line 91, in run
    log=log)
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/qr.py", line 478, in run
    model            = model)
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/qr.py", line 344, in create_restraints_manager
    clustering                 = params.cluster.clustering)
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/restraints.py", line 99, in __init__
    self.charge = charge_service.get_total_charge()
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/charges.py", line 159, in get_total_charge
    verbose=verbose,
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/utils/electrons.py", line 427, in run
    verbose=verbose,
  File "/scratch/roy/programs/phenix-1.16-3549/modules/qrefine/utils/electrons.py", line 74, in __init__
    assert e is not None, ' element %s not found' % atom.element
AssertionError:  element Fe not found

Please guide me to fix this error.

Best regards
Rajeev

**Comment by hokru** [comment]
Currently metal centers need to be handled case-by-case and there may be hurdles to overcome.

Do you know the oxidation number and expected spin-state for the Fe?
One would need to adapt the database here: https://github.com/qrefine/qrefine/blob/master/utils/electrons.py#L21

I am not sure where we are currently standing regarding the handling of open-shell cases.

**Comment by rajeevroy09** [comment]
--Do you know the oxidation number and expected spin-state for the Fe?---
Yes, the Fe is oxidized in this protein hence oxidation number = 3 and its in high spin state. 

--One would need to adapt the database here: https://github.com/qrefine/qrefine/blob/master/utils/electrons.py#L21--
So, it means I can make the possible changes in the "electrons.py" script and try to run the refinement?

**Comment by hokru** [comment]
> So, it means I can make the possible changes in the "electrons.py" script and try to run the refinement?

It only solves a part of the problem.

The main issue is that the fragmentation (aka clustering=true) code is currently unable to switch between closed-shell and open-shell QM calculations as would be needed for non-metal and metal containing fragments.
AFAIK, we have currently no solution to this. Others may correct me, please.

The fragmentation code is needed to expand the unit cell and treat the cell boundary correctly. (until #13 is fixed)

**Comment by mpwaller** [comment]
Hi Rajeev,

Thanks for raising the issue!  As @hokru  said, we need to fix a few things in a few places before qrefine will work with Fe. It will take a number of us to do these modifications, and then we will have to do a little coordination work before the solution will work for you "out of the box".

We are happy to work on this and keep you updated as we make progress. 

In the meantime, feel free to test the system on a protein without Fe to gain some more experience. 

Perhaps you could look at this simple example:

https://github.com/qrefine/qr-tests-cluster/tree/master/planB/2ona

There should be enough instructions on the readme page:

https://github.com/qrefine/qr-tests-cluster

We also have a bit more [documentation](https://qrefine.com/qr.html)  on our [website](https://qrefine.com/).

**Comment by rajeevroy09** [comment]
Thank you Holger and Mark for your time. 

I am keen to work on the proteins containing Fe atoms but meanwhile I will follow your suggestions to test the other systems.
