### ISSUE TITLE
cctbx change (rama z?) breaking parts of finalize.py ?

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#59]
**Describe the bug**
`phenix-1.18rc5-3822` and current qrefine master.

Occurs e.g. for tests 12, 24, 27. Or any qr.finalize run:
```
hokru:kruse :~/QR/tests > qr.finalise x.pdb action="capping"
Starting Q|R finalise
version:   v1.0-176-gc3c7dd-dirty
Traceback (most recent call last):
  File "/Users/kruse/qc/phenix-1.18rc5-3822/build/../modules/qrefine/command_line/finalise.py", line 94, in <module>
    run(args=sys.argv[1:], log=log)
  File "/Users/kruse/qc/phenix-1.18rc5-3822/build/../modules/qrefine/command_line/finalise.py", line 87, in run
    append_to_end_of_model=params.append_to_end_of_model,
  File "/Users/kruse/qc/phenix-1.18rc5-3822/modules/qrefine/finalise.py", line 98, in run
    pdb_hierarchy = ppf.all_chain_proxies.pdb_hierarchy)
TypeError: __init__() got an unexpected keyword argument 'pdb_hierarchy'
```

I see changes that indicate `model` instead of `pdb_hierarchy` as argument for `mmtbx.model.statistics.geometry`.

tagging @pafonine @nwmoriarty

**Comment by pafonine** [comment]
Just fixed.
