### ISSUE TITLE
AQuaref not Ref-ing

### ISSUE THREAD

**Issue by stav-ros** [qrefine/qrefine#92]
**Describe the bug**
Hey, great software but I'm running into the following issue after importing/using a file that came out from phenix refine.

RuntimeError: atom X coordinate value does not fit into F8.3 format:
"ATOM 1 N ALA A 9 "
value: -nan

**To Reproduce**
running qr.refine real_space_refined_004.pdb mapofinterest.mrc engine=aimnet2

**Expected behavior**
Runs up to this point:
cycle: 0
  start: weight=     nan bond: 0.005 angle: 1.11 clash: 6.5 rota: 0.79 rama: f: 97.60 o: 0.06 Z: 0.09 cb: 0.00 shift=0.0000 cc_mask=0.5921
Traceback (most recent call last):
  File "/....software/phenix-dev-5430/build/../modules/qrefine/command_line/qr.py", line 8, in <module>
    run_program(program_class=qr.Program)

.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 24.04]
 - Phenix Version [phenix-dev-5430]
 - qrefine Version 2024.9.dev6+unknown

**Comment by hokru** [comment]
Hi,

The `real_space_refined_004.pdb` comes out of a refinement from `phenix-dev-5430` or another version?
I am asking because the error most likely originates from cctbx.

Would you mind sharing the file or paste a couple of lines of the ATOM here?

**Comment by stav-ros** [comment]
It comes from a previous version... Do we have to refine first using the current Phenix version?

**Comment by hokru** [comment]
No you shouldn't have to. I will investigate with the team.

**Comment by stav-ros** [comment]
Here's the first 25 ATOM lines: 
ATOM      1  N   PRO a 266     141.493 126.178 147.387  1.00168.21           N
ATOM      2  CA  PRO a 266     142.500 126.386 146.343  1.00168.21           C
ATOM      3  C   PRO a 266     141.909 126.889 145.029  1.00168.21           C
ATOM      4  O   PRO a 266     142.405 126.532 143.962  1.00168.21           O
ATOM      5  CB  PRO a 266     143.106 124.989 146.171  1.00168.21           C
ATOM      6  CG  PRO a 266     142.832 124.262 147.484  1.00168.21           C
ATOM      7  CD  PRO a 266     141.904 125.114 148.317  1.00168.21           C
ATOM      8  H2  PRO a 266     140.662 125.928 146.977  1.00168.21           H
ATOM      9  H3  PRO a 266     141.370 126.994 147.874  1.00168.21           H
ATOM     10  HA  PRO a 266     143.183 127.003 146.646  1.00168.21           H
ATOM     11  HB2 PRO a 266     142.669 124.535 145.434  1.00168.21           H
ATOM     12  HB3 PRO a 266     144.060 125.063 146.011  1.00168.21           H
ATOM     13  HG2 PRO a 266     142.423 123.402 147.297  1.00168.21           H
ATOM     14  HG3 PRO a 266     143.672 124.136 147.952  1.00168.21           H
ATOM     15  HD2 PRO a 266     142.384 125.493 149.071  1.00168.21           H
ATOM     16  HD3 PRO a 266     141.135 124.598 148.607  1.00168.21           H
ATOM     17  N   THR a 267     140.861 127.707 145.112  1.00156.58           N
ATOM     18  CA  THR a 267     140.136 128.162 143.932  1.00156.58           C
ATOM     19  C   THR a 267     139.004 129.088 144.356  1.00156.58           C
ATOM     20  O   THR a 267     138.258 128.759 145.279  1.00156.58           O
ATOM     21  CB  THR a 267     139.618 126.948 143.141  1.00156.58           C
ATOM     22  OG1 THR a 267     138.834 127.381 142.021  1.00156.58           O
ATOM     23  CG2 THR a 267     138.849 125.997 144.034  1.00156.58           C
ATOM     24  H   THR a 267     140.546 128.017 145.850  1.00156.58           H

I've now since manually refined in coot and in Phenix (after the update), and trying to see whether than allows the AquaRefinement to go through. 

EDIT:

Failed again. 

``RuntimeError: atom X coordinate value does not fit into F8.3 format:
  "ATOM      1  N   THR C 260 "
  value: -nan

Here's few lines:
ATOM      1  N   THR C 260     132.110 168.024 133.120  1.00 46.84           N  
ATOM      2  CA  THR C 260     131.452 168.813 132.139  1.00 48.27           C  
ATOM      3  C   THR C 260     131.037 169.951 132.965  1.00 48.51           C  
ATOM      4  O   THR C 260     130.375 169.741 133.789  1.00 54.49           O  
ATOM      5  CB  THR C 260     130.265 168.307 131.310  1.00 52.59           C  
ATOM      6  OG1 THR C 260     129.883 166.960 131.301  1.00 63.91           O  
ATOM      7  CG2 THR C 260     130.377 168.590 129.842  1.00 50.35           C  
ATOM      8  N   ASN C 261     131.247 171.092 132.683  1.00 42.92           N

**Comment by georgkempf** [comment]
I ran into the same issue with qrefine built into phenix-2.0rc1-5617 and running this command `qr.refine model.pdb map.mrc  mode=refine engine=aimnet2`

```
  File "phenix/phenix-2.0rc1-5617/modules/qrefine/restraints.py", line 566, in target_and_gradients
    self.pdb_hierarchy.write_pdb_file(file_name=self.file_name)
  File "phenix/phenix-2.0rc1-5617/modules/cctbx_project/iotbx/pdb/hierarchy.py", line 1293, in write_pdb_file
    self._write_pdb_file(
RuntimeError: atom X coordinate value does not fit into F8.3 format:
  "ATOM      1  N   PRO A  39 "
  value: -nan

```

It's the first atom in the file and the actual record looks like this
`ATOM      1  N   PRO A  39     272.911 260.971 281.695  1.00162.91           N`

**Comment by hokru** [comment]
The key error here seems to be: `value: -nan`.  (aka "not a number")
I have seen something like this when `aimnet2` would fail to compute a gradient and just outputs rubbish.

Does your model contain any ligands or non-standard residues?

**Comment by georgkempf** [comment]
Seems like I overlooked the limitation that DNA is not supported...
